version: '3'

services:
  front:
    build: ./docker/front
    environment:
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
      HOST: 0.0.0.0
      PORT: 3030
    volumes:
      - .:/app:cached
      - home_volume:/home/docker
    working_dir: /app
    ports:
      - '3030:3030'
    hostname: front
    entrypoint: ./docker/front/docker-entrypoint.sh
    command: yarn run dev

volumes:
  home_volume:
    driver: local
