version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3-stretch
        environment:
          TZ: Asia/Tokyo

    working_directory: ~/todo-api-rails-front-nuxtjs-sample

    parallelism: 1

    steps:
      - checkout

      # yarn install
      - restore_cache:
          key: todo-api-rails-front-nuxtjs-sample-node-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION }}
      - run:
          name: yarn install
          command: yarn install --ignore-engines
      - save_cache:
          key: todo-api-rails-front-nuxtjs-sample-node-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - ./node_modules

      # run yarn run lint
      - run:
          name: yarn run lint
          command: yarn run lint

      # run yarn run lint:pug-vue
      - run:
          name: yarn run lint:pug-vue
          command: yarn run lint:pug-vue
